import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:get_it/get_it.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:qr_flutter/qr_flutter.dart';

import '../../../../core/settings/settings_repository.dart';
import '../../domain/entity/room_invitation.dart';
import '../../domain/service/room_invite_join_orchestrator.dart';
import '../manager/room_list_cubit.dart';
import '../manager/room_qr_join_carrier.dart';

/// Offline joiner-side QR handshake.
///
/// The first scan only obtains a bearer [RoomInvitation]. The page then shows
/// the correlated request generated by [RoomInviteJoinOrchestrator] as a second
/// QR. Membership is persisted only after the issuer scans that request,
/// verifies/redeems the capability, returns a response QR, and this page scans
/// that response through [RoomQrJoinCarrier].
class RoomQrJoinPage extends StatefulWidget {
  const RoomQrJoinPage({
    required this.cubit,
    required this.settings,
    super.key,
  });

  static Widget buildPage() => BlocProvider<RoomListCubit>(
    create: (_) => GetIt.instance<RoomListCubit>()..load(),
    child: Builder(
      builder: (context) => RoomQrJoinPage(
        cubit: context.read<RoomListCubit>(),
        settings: GetIt.instance<SettingsRepository>(),
      ),
    ),
  );

  final RoomListCubit cubit;
  final SettingsRepository settings;

  @override
  State<RoomQrJoinPage> createState() => _RoomQrJoinPageState();
}

enum _JoinStage { scanInvite, requestQr, scanResponse, finishing, result }

class _RoomQrJoinPageState extends State<RoomQrJoinPage> {
  final RoomQrJoinCarrier _carrier = RoomQrJoinCarrier();
  StreamSubscription<String>? _requestSubscription;
  _JoinStage _stage = _JoinStage.scanInvite;
  String? _requestQr;
  RoomInviteJoinAttemptStatus? _result;
  bool _handlingScan = false;

  bool get _fa =>
      Localizations.localeOf(context).languageCode.toLowerCase() == 'fa';

  @override
  void initState() {
    super.initState();
    _requestSubscription = _carrier.requests.listen((request) {
      if (!mounted) return;
      setState(() {
        _requestQr = request;
        _stage = _JoinStage.requestQr;
      });
    });
  }

  @override
  void dispose() {
    widget.cubit.cancelInviteJoin();
    unawaited(_requestSubscription?.cancel());
    unawaited(_carrier.dispose());
    super.dispose();
  }

  Future<void> _onInviteCapture(BarcodeCapture capture) async {
    if (_handlingScan || _stage != _JoinStage.scanInvite) return;
    final raw = _firstValue(capture);
    if (raw == null) return;
    _handlingScan = true;
    try {
      final invitation = RoomInvitation.decode(raw);
      var displayName = (await widget.settings.getMyName()).trim();
      if (displayName.isEmpty) displayName = _fa ? 'همراه' : 'Rider';
      if (!mounted) return;
      final attempt = widget.cubit.joinByInvite(
        invitation: invitation,
        displayName: displayName,
        carrier: _carrier,
      );
      final result = await attempt;
      if (!mounted) return;
      setState(() {
        _result = result;
        _stage = _JoinStage.result;
      });
    } on FormatException {
      if (mounted) {
        _showInvalid(_fa ? 'دعوت نامعتبر است.' : 'Invalid Room invite.');
      }
    } catch (_) {
      if (mounted) {
        _showInvalid(
          _fa ? 'خواندن دعوت ممکن نشد.' : 'Could not read the Room invite.',
        );
      }
    } finally {
      _handlingScan = false;
    }
  }

  void _onResponseCapture(BarcodeCapture capture) {
    if (_handlingScan || _stage != _JoinStage.scanResponse) return;
    final raw = _firstValue(capture);
    if (raw == null) return;
    _handlingScan = true;
    if (_carrier.submitResponse(raw)) {
      setState(() => _stage = _JoinStage.finishing);
    } else {
      _handlingScan = false;
    }
  }

  String? _firstValue(BarcodeCapture capture) {
    for (final barcode in capture.barcodes) {
      final value = barcode.rawValue?.trim();
      if (value != null && value.isNotEmpty) return value;
    }
    return null;
  }

  void _showInvalid(String message) {
    ScaffoldMessenger.of(context)
      ..hideCurrentSnackBar()
      ..showSnackBar(SnackBar(content: Text(message)));
  }

  @override
  Widget build(BuildContext context) {
    final title = _fa ? 'پیوستن امن به اتاق' : 'Secure Room join';
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: SafeArea(child: _body()),
    );
  }

  Widget _body() => switch (_stage) {
    _JoinStage.scanInvite => _scanner(
      key: const Key('room-join-scan-invite'),
      instruction: _fa
          ? 'QR دعوت اتاق را اسکن کنید. اسکن به‌تنهایی عضویت را تأیید نمی‌کند.'
          : 'Scan the Room invite QR. Scanning alone does not authorize membership.',
      onDetect: _onInviteCapture,
    ),
    _JoinStage.requestQr => _requestView(),
    _JoinStage.scanResponse => _scanner(
      key: const Key('room-join-scan-response'),
      instruction: _fa
          ? 'حالا QR پاسخ تأییدشده روی گوشی دعوت‌کننده را اسکن کنید.'
          : 'Now scan the verified response QR shown on the inviter phone.',
      onDetect: _onResponseCapture,
    ),
    _JoinStage.finishing => const Center(child: CircularProgressIndicator()),
    _JoinStage.result => _resultView(),
  };

  Widget _scanner({
    required Key key,
    required String instruction,
    required void Function(BarcodeCapture) onDetect,
  }) => Column(
    key: key,
    children: [
      Padding(
        padding: const EdgeInsets.all(20),
        child: Text(instruction, textAlign: TextAlign.center),
      ),
      Expanded(
        child: Semantics(
          label: instruction,
          child: MobileScanner(onDetect: onDetect),
        ),
      ),
    ],
  );

  Widget _requestView() {
    final request = _requestQr;
    if (request == null) return const Center(child: CircularProgressIndicator());
    return ListView(
      key: const Key('room-join-request-qr'),
      padding: const EdgeInsets.all(20),
      children: [
        Text(
          _fa
              ? 'این QR درخواست عضویت است. دعوت‌کننده باید آن را اسکن و روی گوشی خودش تأیید کند.'
              : 'This QR is a membership request. The inviter must scan and verify it on their phone.',
          textAlign: TextAlign.center,
        ),
        const SizedBox(height: 20),
        Center(child: _QrPayload(data: request)),
        const SizedBox(height: 20),
        FilledButton.icon(
          key: const Key('room-join-scan-issuer-response'),
          onPressed: () => setState(() => _stage = _JoinStage.scanResponse),
          icon: const Icon(Icons.qr_code_scanner_rounded),
          label: Text(_fa ? 'اسکن پاسخ دعوت‌کننده' : 'Scan inviter response'),
        ),
      ],
    );
  }

  Widget _resultView() {
    final success = _result == RoomInviteJoinAttemptStatus.accepted;
    final text = success
        ? (_fa
              ? 'عضویت تأیید و اتاق ذخیره شد.'
              : 'Membership verified and Room saved.')
        : (_fa
              ? 'عضویت تأیید نشد. هیچ اتاقی از این تلاش ذخیره نشد.'
              : 'Join was not verified. No Room was saved from this attempt.');
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              success ? Icons.check_circle_outline : Icons.error_outline,
              size: 48,
            ),
            const SizedBox(height: 12),
            Text(text, textAlign: TextAlign.center),
            const SizedBox(height: 20),
            FilledButton(
              key: const Key('room-join-done'),
              onPressed: () => Navigator.of(context).pop(success),
              child: Text(_fa ? 'تمام' : 'Done'),
            ),
          ],
        ),
      ),
    );
  }
}

class _QrPayload extends StatelessWidget {
  const _QrPayload({required this.data});

  final String data;

  @override
  Widget build(BuildContext context) => Container(
    width: 260,
    height: 260,
    padding: const EdgeInsets.all(12),
    color: Colors.white,
    child: QrImageView(
      data: data,
      size: 236,
      backgroundColor: Colors.white,
      eyeStyle: const QrEyeStyle(color: Colors.black),
      dataModuleStyle: const QrDataModuleStyle(color: Colors.black),
    ),
  );
}
