import 'dart:convert';

// crypto is already locked transitively in this repository; keeping this
// focused security fix dependency-neutral avoids rewriting the lockfile while
// still using a standard SHA-256 verifier instead of a custom hash.
// ignore: depend_on_referenced_packages
import 'package:crypto/crypto.dart';

import '../entity/room_invitation.dart';

enum RoomInvitationDecision {
  accepted,
  expired,
  revoked,
  replayed,
  invalidCapability,
}

/// Issuer/local-peer revocation, verification and replay ledger for offline
/// Room invites.
///
/// A syntactically valid QR is not enough to authorize membership. The issuer
/// must first register the capability it created; evaluation then compares a
/// SHA-256 verifier of the presented bearer secret with the stored verifier.
/// Raw invite secrets are never persisted by this ledger.
///
/// Revocation is deterministic on peers that have received this state. It
/// cannot pretend to provide instantaneous global revocation while every
/// device is offline.
final class RoomInvitationLedger {
  RoomInvitationLedger({
    Map<String, String> issuedVerifiers = const {},
    Iterable<String> revoked = const [],
    Iterable<String> redeemed = const [],
  }) : _issuedVerifiers = {...issuedVerifiers},
       _revoked = {...revoked},
       _redeemed = {...redeemed};

  final Map<String, String> _issuedVerifiers;
  final Set<String> _revoked;
  final Set<String> _redeemed;

  Set<String> get issuedIds => Set.unmodifiable(_issuedVerifiers.keys.toSet());
  Set<String> get revokedIds => Set.unmodifiable(_revoked);
  Set<String> get redeemedIds => Set.unmodifiable(_redeemed);

  /// Registers a capability generated by this Room issuer.
  ///
  /// Persist only the verifier; callers continue to share the original bearer
  /// secret through the encoded QR/link itself.
  void registerIssued(RoomInvitation invite) {
    _issuedVerifiers[invite.invitationId] = _secretVerifier(invite.secret);
  }

  void revoke(RoomInvitation invite) => _revoked.add(invite.invitationId);

  RoomInvitationDecision evaluate(RoomInvitation invite, DateTime now) {
    final verifier = _issuedVerifiers[invite.invitationId];
    if (verifier == null || !_matchesVerifier(verifier, invite.secret)) {
      return RoomInvitationDecision.invalidCapability;
    }
    if (_revoked.contains(invite.invitationId)) {
      return RoomInvitationDecision.revoked;
    }
    if (invite.singleUse && _redeemed.contains(invite.invitationId)) {
      return RoomInvitationDecision.replayed;
    }
    if (!now.toUtc().isBefore(invite.expiresAt)) {
      return RoomInvitationDecision.expired;
    }
    return RoomInvitationDecision.accepted;
  }

  RoomInvitationDecision redeem(RoomInvitation invite, DateTime now) {
    final decision = evaluate(invite, now);
    if (decision == RoomInvitationDecision.accepted && invite.singleUse) {
      _redeemed.add(invite.invitationId);
    }
    return decision;
  }

  /// State v2 adds issuer-side capability verifiers. v1 remains decodable but
  /// fails closed for authorization because it did not contain proof that an
  /// invite was actually issued by this Room.
  String encodeState() => jsonEncode({
    'v': 2,
    'issued': Map.fromEntries(
      _issuedVerifiers.entries.toList()
        ..sort((left, right) => left.key.compareTo(right.key)),
    ),
    'revoked': _revoked.toList()..sort(),
    'redeemed': _redeemed.toList()..sort(),
  });

  static RoomInvitationLedger decodeState(String raw) {
    try {
      final value = jsonDecode(raw);
      if (value is! Map<String, dynamic>) {
        throw const FormatException('invite ledger object');
      }
      final version = value['v'];
      if (version != 1 && version != 2) {
        throw const FormatException('invite ledger version');
      }
      final revoked = value['revoked'];
      final redeemed = value['redeemed'];
      if (revoked is! List || redeemed is! List) {
        throw const FormatException('invite ledger fields');
      }

      String validateId(Object? value) {
        if (value is! String || !RegExp(r'^[0-9a-f]{32}$').hasMatch(value)) {
          throw const FormatException('invite ledger id');
        }
        return value;
      }

      final issued = <String, String>{};
      if (version == 2) {
        final rawIssued = value['issued'];
        if (rawIssued is! Map<String, dynamic>) {
          throw const FormatException('invite ledger issued');
        }
        for (final entry in rawIssued.entries) {
          final id = validateId(entry.key);
          final verifier = entry.value;
          if (verifier is! String ||
              !RegExp(r'^[0-9a-f]{64}$').hasMatch(verifier)) {
            throw const FormatException('invite ledger verifier');
          }
          issued[id] = verifier;
        }
      }

      return RoomInvitationLedger(
        issuedVerifiers: issued,
        revoked: revoked.map(validateId),
        redeemed: redeemed.map(validateId),
      );
    } on FormatException {
      rethrow;
    } catch (_) {
      throw const FormatException('malformed invite ledger');
    }
  }

  static String _secretVerifier(String secret) =>
      sha256.convert(utf8.encode(secret)).toString();

  static bool _matchesVerifier(String expected, String secret) {
    final actual = _secretVerifier(secret);
    if (actual.length != expected.length) return false;
    var mismatch = 0;
    for (var i = 0; i < expected.length; i++) {
      mismatch |= expected.codeUnitAt(i) ^ actual.codeUnitAt(i);
    }
    return mismatch == 0;
  }
}
